.global: &global
  only:
    refs:
      - branches
    changes:
      - .gitlab-ci.yml
      - go.mod
      - go.sum
      - '**/*.go'

.amd64: &amd64
  variables:
    VGOOS: linux
    VGOARCH: amd64

.i386: &i386
  variables:
    VGOOS: linux
    VGOARCH: 386

.unit.test.script.cover: &script_cover
  script:
    - GOOS=${VGOOS} GOARCH=${VGOARCH} go test -cover -v -bench . -benchmem ./...

go.1.5 unit.test 1/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .amd64
  image: golang:1.5-alpine

go.1.5 unit.test 2/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .i386
  image: golang:1.5-alpine

go.1.6 unit.test 1/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .amd64
  image: golang:1.6-alpine

go.1.6 unit.test 2/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .i386
  image: golang:1.6-alpine

go.1.7 unit.test 1/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .amd64
  image: golang:1.7-alpine

go.1.7 unit.test 2/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .i386
  image: golang:1.7-alpine

go.1.8 unit.test 1/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .amd64
  image: golang:1.8-alpine

go.1.8 unit.test 2/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .i386
  image: golang:1.8-alpine

go.1.9 unit.test 1/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .amd64
  image: golang:1.9-alpine

go.1.9 unit.test 2/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .i386
  image: golang:1.9-alpine

go.1.10 unit.test 1/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .amd64
  image: golang:1.10-alpine

go.1.10 unit.test 2/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .i386
  image: golang:1.10-alpine

go.1.11 unit.test 1/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .amd64
  image: golang:1.11-alpine

go.1.11 unit.test 2/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .i386
  image: golang:1.11-alpine

go.1.12 unit.test 1/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .amd64
  image: golang:1.12-alpine

go.1.12 unit.test 2/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .i386
  image: golang:1.12-alpine

go.1.13 unit.test 1/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .amd64
  image: golang:1.13-alpine

go.1.13 unit.test 2/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .i386
  image: golang:1.13-alpine

go.1.14 unit.test 1/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .amd64
  image: golang:1.14-alpine

go.1.14 unit.test 2/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .i386
  image: golang:1.14-alpine

go.1.15 unit.test 1/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .amd64
  image: golang:1.15-alpine

go.1.15 unit.test 2/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .i386
  image: golang:1.15-alpine

go.1.16 unit.test 1/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .amd64
  image: golang:1.16-alpine

go.1.16 unit.test 2/2:
  extends:
    - .global
    - .unit.test.script.cover
    - .i386
  image: golang:1.16-alpine
